# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Update Notion Data

on:
  schedule:
    # every 6 hours
#     - cron: "0 */6 * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Update notion data
      run: |
          bash ./main.sh 2>> /tmp/apidata_err
          echo "the job completed"
      env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_VERSION: ${{ secrets.NOTION_VERSION }}
          NAVGURUKUL_DB_ID: ${{ secrets.NAVGURUKUL_DB_ID }}
